name: Terraform CI

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Terraform Init
  run: terraform init
  working-directory: terraform

- name: Terraform Plan
  run: terraform plan
  working-directory: terraform

- name: Terraform Validate
  run: terraform validate
  working-directory: terraform

- name: Terraform Format Check
  run: terraform fmt -check
  working-directory: terraform
